# Generated by Django 2.2.6 on 2020-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性'), ('非公開', '非公開')], default='非公開', max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ニックネーム'),
        ),
    ]
