# Generated by Django 2.2.6 on 2020-01-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djappy', '0004_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
